### ISSUE TITLE
Full support for fixed version Lerna monorepos

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/node-versioner#15]
* [x] Changed package detection
* [x] NPM package publishing
* [x] Automatic version bumps
* [x] Automatic changelog updates
* [ ] Re-detect changed packages after version bumps
* [ ] Prepublish action
* [ ] GitHub artifact publishing

**Comment by t1m0thyj** [comment]
Closing as out of scope. Planning to keep the intent of this action simple to publish a single package.

**Comment by t1m0thyj** [comment]
[ ] Attempt to publish all packages, not just changed ones
[ ] Use output from update-npm-deps action to skip this one
[ ] Fix output of lerna changed creating error
[ ] Comment on PR after successful publish

**Comment by t1m0thyj** [comment]
Created separate issues to track tasks that are still relevant
