### ISSUE TITLE
Should release-XXX labels be deleted after version stage finishes?

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/node-versioner#4]
Currently, if deploy job has already run successfully once, and is re-run for a PR with a "release-XXX" label, the version would get bumped a second time.

**Comment by t1m0thyj** [comment]
Could also add a "released" label to the PR after a successful publish like semantic-release does

**Comment by t1m0thyj** [comment]
> Could also add a "released" label to the PR after a successful publish like semantic-release does

This has been done, what remains is to check the presence of this label and stop the build if it already is present.
